awhs_wake_homepage:
    path:     /
    defaults:
            _controller: FrameworkBundle:Redirect:redirect
            route: awhs_wake_computers
            permanent: true
awhs_wake_computers:
    path:     /computers
    defaults: { _controller: AWHSWakeBundle:Default:computers }
awhs_wake_computer_wake:
    path:     /computer/{computer_id}-{computer_name}/wake
    defaults: { _controller: AWHSWakeBundle:Default:wake }
awhs_wake_computer_schedules:
    path:     /computer/{computer_id}-{computer_name}/schedules
    defaults: { _controller: AWHSWakeBundle:Default:schedules }
awhs_wake_computer_schedule_delete:
    path:     /computer/{computer_id}/schedule/{schedule_id}/delete
    defaults: { _controller: AWHSWakeBundle:Default:deleteSchedule }
awhs_wake_computer_delete:
    path:     /computer/{computer_id}/delete
    defaults: { _controller: AWHSWakeBundle:Default:deleteComputer }
awhs_wake_computer_stats:
    path:     /computer/{computer_id}-{computer_name}/stats
    defaults: { _controller: AWHSWakeBundle:Default:stats }
awhs_wake_computer_stats_json:
    path:     /computer/{computer_id}-{computer_name}/stats/json
    defaults: { _controller: AWHSWakeBundle:Default:statsJson }
awhs_wake_computer_stat_update:
    path:     /{userKey}/computer/{computer_id}-{computer_name}/stats/update
    defaults: { _controller: AWHSWakeBundle:Default:statsUpdate }