awhs_wake_homepage:
    path:     /
    defaults:
            _controller: FrameworkBundle:Redirect:redirect
            route: awhs_wake_computers
            permanent: true
awhs_wake_computers:
    path:     /computers
    defaults: { _controller: AWHSWakeBundle:Default:computers }
awhs_wake_computer_wake:
    path:     /computer/{computer_id}-{computer_name}/wake
    defaults: { _controller: AWHSWakeBundle:Default:wake }
awhs_wake_computer_schedules:
    path:     /computer/{computer_id}-{computer_name}/schedules
    defaults: { _controller: AWHSWakeBundle:Default:schedules }
awhs_wake_computer_schedule_delete:
    path:     /computer/{computer_id}/schedule/{schedule_id}/delete
    defaults: { _controller: AWHSWakeBundle:Default:deleteSchedule }
awhs_wake_computer_delete:
    path:     /computer/{computer_id}/delete
    defaults: { _controller: AWHSWakeBundle:Default:deleteComputer }
